### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by retorquere** [andersjohansson/zotero-biblatex-translator#4]
Hello Anders,

I am working on a plugin that loads extra translators into Zotero (http://goo.gl/AdviUn); one of the translators it loads is an adapted version of your BibLaTeX translator. Would you care to work together?

**Comment by andersjohansson** [comment]
Closing this. I am only using BetterBibTex now. Thanks for all your work with it!

**Comment by retorquere** [comment]
It is my pleasure.
